using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using ElectroMart.API.Data;
using ElectroMart.API.DTOs;
using ElectroMart.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace ElectroMart.API.Services;
public class CommerceService(ApplicationDbContext db, IConfiguration config)
{
    public async Task<AuthResponse?> Login(LoginRequest r) { var u=await db.Users.FirstOrDefaultAsync(x=>x.Email==r.Email.ToLower()); if(u is null || !BCrypt.Net.BCrypt.Verify(r.Password,u.PasswordHash)) return null; return Token(u); }
    public async Task<AuthResponse> Register(RegisterRequest r) { var email=r.Email.Trim().ToLower(); if(await db.Users.AnyAsync(x=>x.Email==email)) throw new InvalidOperationException("Email is already registered."); var u=new User{FirstName=r.FirstName,LastName=r.LastName,Email=email,PasswordHash=BCrypt.Net.BCrypt.HashPassword(r.Password)}; db.Users.Add(u); await db.SaveChangesAsync(); return Token(u); }
    public UserDto ToUser(User u)=>new(u.Id,u.FirstName,u.LastName,u.Email,u.Role.ToString(),u.PhoneNumber,u.Address,u.City,u.State,u.PostalCode);
    AuthResponse Token(User u){ var claims=new[]{new Claim(ClaimTypes.NameIdentifier,u.Id.ToString()),new Claim(ClaimTypes.Email,u.Email),new Claim(ClaimTypes.Role,u.Role.ToString())}; var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:Key"]!)); var token=new JwtSecurityToken(config["Jwt:Issuer"],config["Jwt:Audience"],claims,expires:DateTime.UtcNow.AddMinutes(config.GetValue("Jwt:ExpirationMinutes",120)),signingCredentials:new SigningCredentials(key,SecurityAlgorithms.HmacSha256)); return new(new JwtSecurityTokenHandler().WriteToken(token),ToUser(u)); }
    public async Task<List<CategoryDto>> Categories()=>await db.Categories.AsNoTracking().Select(x=>new CategoryDto(x.Id,x.Name,x.Description,x.ImageUrl,x.IsActive)).ToListAsync();
    public async Task<CategoryDto?> Category(int id)=>await db.Categories.Where(x=>x.Id==id).Select(x=>new CategoryDto(x.Id,x.Name,x.Description,x.ImageUrl,x.IsActive)).FirstOrDefaultAsync();
    public async Task<List<ProductDto>> Products(string? search,int? categoryId,string? brand,decimal? minPrice,decimal? maxPrice,string? sortBy,int pageNumber=1,int pageSize=12){ var q=db.Products.AsNoTracking().Include(x=>x.Category).Where(x=>x.IsActive); if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Name.Contains(search)||x.Brand.Contains(search)||x.Category!.Name.Contains(search)); if(categoryId.HasValue)q=q.Where(x=>x.CategoryId==categoryId); if(!string.IsNullOrWhiteSpace(brand))q=q.Where(x=>x.Brand==brand); if(minPrice.HasValue)q=q.Where(x=>(x.DiscountPrice??x.Price)>=minPrice); if(maxPrice.HasValue)q=q.Where(x=>(x.DiscountPrice??x.Price)<=maxPrice); q=sortBy switch {"priceAsc"=>q.OrderBy(x=>x.DiscountPrice??x.Price),"priceDesc"=>q.OrderByDescending(x=>x.DiscountPrice??x.Price),"name"=>q.OrderBy(x=>x.Name),_=>q.OrderByDescending(x=>x.CreatedAt)}; return await q.Skip((pageNumber-1)*pageSize).Take(Math.Min(pageSize,50)).Select(x=>new ProductDto(x.Id,x.Name,x.Brand,x.Description,x.Price,x.DiscountPrice,x.StockQuantity,x.ImageUrl,x.CategoryId,x.Category!.Name,x.IsFeatured,x.IsActive,x.Specifications,x.CreatedAt)).ToListAsync(); }
    public async Task<ProductDto?> Product(int id)=>await db.Products.Include(x=>x.Category).Where(x=>x.Id==id).Select(x=>new ProductDto(x.Id,x.Name,x.Brand,x.Description,x.Price,x.DiscountPrice,x.StockQuantity,x.ImageUrl,x.CategoryId,x.Category!.Name,x.IsFeatured,x.IsActive,x.Specifications,x.CreatedAt)).FirstOrDefaultAsync();
    public async Task<CartDto> Cart(int uid){var c=await GetCart(uid);return MapCart(c);} async Task<Cart> GetCart(int uid){var c=await db.Carts.Include(x=>x.Items).ThenInclude(x=>x.Product).SingleOrDefaultAsync(x=>x.UserId==uid);if(c!=null)return c;c=new Cart{UserId=uid};db.Carts.Add(c);await db.SaveChangesAsync();return c;}
    CartDto MapCart(Cart c)=>new(c.Id,c.Items.Select(i=>new CartItemDto(i.Id,i.ProductId,i.Product!.Name,i.Product.ImageUrl,i.Quantity,i.UnitPrice,i.UnitPrice*i.Quantity,i.Product.StockQuantity)),c.Items.Sum(i=>i.UnitPrice*i.Quantity));
    public async Task<CartDto> AddItem(int uid,AddCartItemRequest r){var c=await GetCart(uid);var p=await db.Products.FindAsync(r.ProductId)??throw new KeyNotFoundException("Product not found.");var item=c.Items.FirstOrDefault(x=>x.ProductId==r.ProductId);if((item?.Quantity??0)+r.Quantity>p.StockQuantity)throw new InvalidOperationException("Requested quantity exceeds available stock.");if(item==null)c.Items.Add(new CartItem{ProductId=p.Id,Quantity=r.Quantity,UnitPrice=p.DiscountPrice??p.Price,Product=p});else item.Quantity+=r.Quantity;c.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return MapCart(await GetCart(uid));}
    public async Task<CartDto> UpdateItem(int uid,int id,UpdateCartItemRequest r){var c=await GetCart(uid);var i=c.Items.FirstOrDefault(x=>x.Id==id)??throw new KeyNotFoundException("Cart item not found.");if(r.Quantity>i.Product!.StockQuantity)throw new InvalidOperationException("Requested quantity exceeds available stock.");i.Quantity=r.Quantity;await db.SaveChangesAsync();return MapCart(c);}
    public async Task<CartDto> RemoveItem(int uid,int id){var c=await GetCart(uid);var i=c.Items.FirstOrDefault(x=>x.Id==id);if(i!=null)db.CartItems.Remove(i);await db.SaveChangesAsync();return MapCart(await GetCart(uid));}
    public async Task<CartDto> Clear(int uid){var c=await GetCart(uid);db.CartItems.RemoveRange(c.Items);await db.SaveChangesAsync();return MapCart(await GetCart(uid));}
    public async Task<OrderDto> Checkout(int uid,CheckoutRequest r){var c=await GetCart(uid);if(!c.Items.Any())throw new InvalidOperationException("Cart is empty.");await using var tx=await db.Database.BeginTransactionAsync();foreach(var i in c.Items){var p=await db.Products.FindAsync(i.ProductId)??throw new InvalidOperationException("A product is no longer available.");if(i.Quantity>p.StockQuantity)throw new InvalidOperationException($"Insufficient stock for {p.Name}.");}var order=new Order{UserId=uid,OrderNumber=$"ORD-{DateTime.UtcNow:yyyyMMdd}-{Random.Shared.Next(1,9999):D4}",ShippingAddress=r.ShippingAddress,PaymentMethod=r.PaymentMethod,TotalAmount=c.Items.Sum(i=>i.UnitPrice*i.Quantity)};foreach(var i in c.Items){var p=await db.Products.FindAsync(i.ProductId)!;p!.StockQuantity-=i.Quantity;order.Items.Add(new OrderItem{ProductId=p.Id,ProductName=p.Name,ProductImageUrl=p.ImageUrl,UnitPrice=i.UnitPrice,Quantity=i.Quantity,Subtotal=i.UnitPrice*i.Quantity});}db.Orders.Add(order);db.CartItems.RemoveRange(c.Items);await db.SaveChangesAsync();await tx.CommitAsync();return MapOrder(order);}
    OrderDto MapOrder(Order o)=>new(o.Id,o.OrderNumber,o.TotalAmount,o.ShippingAddress,o.PaymentMethod,o.PaymentStatus.ToString(),o.OrderStatus.ToString(),o.CreatedAt,o.Items.Select(i=>new OrderItemDto(i.ProductId,i.ProductName,i.ProductImageUrl,i.UnitPrice,i.Quantity,i.Subtotal)));
    public async Task<List<OrderDto>> Orders(int? uid=null){var q=db.Orders.Include(x=>x.Items).AsNoTracking();if(uid.HasValue)q=q.Where(x=>x.UserId==uid);return (await q.OrderByDescending(x=>x.CreatedAt).ToListAsync()).Select(MapOrder).ToList();}
    public async Task<OrderDto?> Order(int id,int? uid=null){var o=await db.Orders.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==id&&(uid==null||x.UserId==uid));return o==null?null:MapOrder(o);}
    public async Task<OrderDto?> Status(int id,OrderStatus s){var o=await db.Orders.Include(x=>x.Items).FirstOrDefaultAsync(x=>x.Id==id);if(o==null)return null;o.OrderStatus=s;o.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return MapOrder(o);}
}
