using ElectroMart.API.Data; using ElectroMart.API.DTOs; using ElectroMart.API.Models; using ElectroMart.API.Services; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace ElectroMart.API.Controllers;
[ApiController,Route("api/categories")] public class CategoriesController(CommerceService s,ApplicationDbContext db):ControllerBase{
 [HttpGet] public async Task<IActionResult> Get()=>Ok(await s.Categories()); [HttpGet("{id:int}")] public async Task<IActionResult> Get(int id)=> (await s.Category(id)) is{} x?Ok(x):NotFound();
 [Authorize(Roles="Admin"),HttpPost] public async Task<IActionResult> Post(CategoryRequest r){var c=new Category{Name=r.Name,Description=r.Description,ImageUrl=r.ImageUrl,IsActive=r.IsActive};db.Categories.Add(c);await db.SaveChangesAsync();return CreatedAtAction(nameof(Get),new{id=c.Id},await s.Category(c.Id));}
 [Authorize(Roles="Admin"),HttpPut("{id:int}")] public async Task<IActionResult> Put(int id,CategoryRequest r){var c=await db.Categories.FindAsync(id);if(c==null)return NotFound();c.Name=r.Name;c.Description=r.Description;c.ImageUrl=r.ImageUrl;c.IsActive=r.IsActive;await db.SaveChangesAsync();return Ok(await s.Category(id));}
 [Authorize(Roles="Admin"),HttpDelete("{id:int}")] public async Task<IActionResult> Delete(int id){var c=await db.Categories.FindAsync(id);if(c==null)return NotFound();c.IsActive=false;await db.SaveChangesAsync();return NoContent();}
}
[ApiController,Route("api/products")] public class ProductsController(CommerceService s,ApplicationDbContext db):ControllerBase{
 [HttpGet] public async Task<IActionResult> Get(string? search,int? categoryId,string? brand,decimal? minPrice,decimal? maxPrice,string? sortBy,int pageNumber=1,int pageSize=12)=>Ok(new{items=await s.Products(search,categoryId,brand,minPrice,maxPrice,sortBy,pageNumber,pageSize),pageNumber,pageSize});
 [HttpGet("featured")] public async Task<IActionResult> Featured()=>Ok(await s.Products(null,null,null,null,null,"newest",1,8)); [HttpGet("{id:int}")] public async Task<IActionResult> Get(int id)=>(await s.Product(id)) is{} x?Ok(x):NotFound();
 [Authorize(Roles="Admin"),HttpPost] public async Task<IActionResult> Post(ProductRequest r){var p=new Product{Name=r.Name,Brand=r.Brand,Description=r.Description,Price=r.Price,DiscountPrice=r.DiscountPrice,StockQuantity=r.StockQuantity,ImageUrl=r.ImageUrl,CategoryId=r.CategoryId,IsFeatured=r.IsFeatured,IsActive=r.IsActive,Specifications=r.Specifications};db.Products.Add(p);await db.SaveChangesAsync();return CreatedAtAction(nameof(Get),new{id=p.Id},await s.Product(p.Id));}
 [Authorize(Roles="Admin"),HttpPut("{id:int}")] public async Task<IActionResult> Put(int id,ProductRequest r){var p=await db.Products.FindAsync(id);if(p==null)return NotFound();p.Name=r.Name;p.Brand=r.Brand;p.Description=r.Description;p.Price=r.Price;p.DiscountPrice=r.DiscountPrice;p.StockQuantity=r.StockQuantity;p.ImageUrl=r.ImageUrl;p.CategoryId=r.CategoryId;p.IsFeatured=r.IsFeatured;p.IsActive=r.IsActive;p.Specifications=r.Specifications;p.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Ok(await s.Product(id));}
 [Authorize(Roles="Admin"),HttpDelete("{id:int}")] public async Task<IActionResult> Delete(int id){var p=await db.Products.FindAsync(id);if(p==null)return NotFound();p.IsActive=false;await db.SaveChangesAsync();return NoContent();}
}
